
/*CREATE TABLE USER_DETAILS(
 USER_ID VARCHAR(40) NOT NULL,
  USER_NAME VARCHAR(9) NOT NULL,
  PASSWORD VARCHAR(4) NOT NULL,
  PREFERRED_PHONE INTEGER (10),
  EMAIL_ADDRESS VARCHAR(35),  
  PRIMARY KEY (USER_ID)
);

CREATE TABLE PHONE_DETAILS (
  PHONE_ID VARCHAR(40) NOT NULL,
  PHONE_NUMBER INTEGER (10) ,
  PHONE_MODEL VARCHAR(20),
  PHONE_NAME VARCHAR(20),
  PREFERRED_IND VARCHAR(1) DEFAULT 'N',
  USER_ID VARCHAR(40),
  PRIMARY KEY (PHONE_ID)
  CONSTRAINT user_fk FOREIGN KEY (USER_ID)
    REFERENCES USER_DETAILS(USER_ID)
);*/